#ifndef __GE_INCLUDES_HPP__
#define __GE_INCLUDES_HPP__
#include <ge/core/application.hpp>
#include <ge/inputs/controller_events.hpp>
#include <ge/inputs/controller_input.hpp>
#include <ge/inputs/global_events.hpp>
#include <ge/graphics/image.hpp>
#include <ge/core/window.hpp>
#include <ge/inputs/key_combo.hpp>
#include <ge/inputs/key_events.hpp>
#include <ge/inputs/key_input.hpp>
#include <ge/utils/log.hpp>
#include <ge/inputs/monitor.hpp>
#include <ge/inputs/mouse_events.hpp>
#include <ge/inputs/mouse_input.hpp>
#include <ge/core/timing.hpp>
#include <ge/inputs/clipboard.hpp>
#include <ge/core/scene.hpp>
#include <ge/core/scene_manager.hpp>
#include <ge/utils/colors.hpp>
#include <ge/graphics/shader.hpp>
#include <ge/graphics/mesh.hpp>
#include <ge/graphics/renderer.hpp>
#include <ge/graphics/camera2D.hpp>
#include <ge/entity/transform.hpp>
#include <ge/utils/utils.hpp>
#include <ge/entity/game_object.hpp>
#include <ge/entity/components/component.hpp>
#include <ge/entity/components/callback_component.hpp>
#include <ge/entity/components/move_component.hpp>
#include <ge/entity/components/events/events.hpp>
#include <ge/entity/components/events_components.hpp>
#endif
