#ifndef __GE_INCLUDES_HPP__
#define __GE_INCLUDES_HPP__
#include <ge/core/application.hpp>
#include <ge/inputs/controller_events.hpp>
#include <ge/inputs/controller_input.hpp>
#include <ge/inputs/global_events.hpp>
#include <ge/graphics/image.hpp>
#include <ge/core/window.hpp>
#include <ge/inputs/key_combo.hpp>
#include <ge/inputs/key_events.hpp>
#include <ge/inputs/key_input.hpp>
#include <ge/utils/log.hpp>
#include <ge/inputs/monitor.hpp>
#include <ge/inputs/mouse_events.hpp>
#include <ge/inputs/mouse_input.hpp>
#include <ge/core/timing.hpp>
#include <ge/inputs/clipboard.hpp>
#include <ge/core/scene.hpp>
#include <ge/core/scene_manager.hpp>
#include <ge/utils/colors.hpp>
#include <ge/graphics/shader.hpp>
#include <ge/graphics/mesh.hpp>
#include <ge/graphics/renderer.hpp>
#include <ge/graphics/camera2D.hpp>
#include <ge/entity/transform.hpp>
#include <ge/utils/utils.hpp>
#include <ge/entity/game_object.hpp>
#include <ge/entity/components/component.hpp>
#include <ge/entity/components/callback_component.hpp>
#include <ge/entity/components/move_component.hpp>
#include <ge/entity/components/events/events.hpp>
#include <ge/entity/components/events_components.hpp>
#include <ge/entity/components/collider_component.hpp>
#include <ge/entity/components/sprite_component.hpp>
#include <ge/entity/components/shape_properties_component.hpp>
#include <ge/entity/components/color_properties_component.hpp>
#include <ge/entity/components/text_properties_component.hpp>
#include <ge/core/spritesheet_manager.hpp>
#include <ge/graphics/text/font.hpp>
#include <ge/entity/text.hpp>
#include <ge/entity/circle.hpp>
#include <ge/entity/rect.hpp>
#include <ge/entity/node.hpp>
#include <ge/graphics/sprite_sheet.hpp>
#include <ge/binding/property.hpp>
#include <ge/binding/notify_property.hpp>
#include <ge/timer/timer.hpp>
#include <ge/entity/components/timer_component.hpp>
#include <ge/tween/tween_functions.hpp>
#include <ge/tween/tween.hpp>
#include <ge/tween/animation.hpp>
#include <ge/entity/components/animation_component.hpp>
#include <ge/entity/components/renderer_component.hpp>
#include <ge/entity/ui/button.hpp>
#endif
