#ifndef __GE_INCLUDES_HPP__
#define __GE_INCLUDES_HPP__
#include <application.hpp>
#include <controller_events.hpp>
#include <controller_input.hpp>
#include <global_events.hpp>
#include <image.hpp>
#include <window.hpp>
#include <key_combo.hpp>
#include <key_events.hpp>
#include <key_input.hpp>
#include <log.hpp>
#include <monitor.hpp>
#include <mouse_events.hpp>
#include <mouse_input.hpp>
#include <timing.hpp>
#include <clipboard.hpp>
#include <scene.hpp>
#include <scene_manager.hpp>
#include <colors.hpp>
#include <shader.hpp>
#include <mesh.hpp>
#include <renderer.hpp>
#include <camera2D.hpp>
#include <transform.hpp>
#include <utils.hpp>
#endif
